# --- Plugin metadata ---
pluginGroup=dev.owlmajin.project.switcher
pluginName=Project Switcher
pluginVersion=2.1.0
pluginRepositoryUrl=https://github.com/WordyArc/ProjectSwitcher

# --- IntelliJ Platform ---
platformVersion=253.28294.325
pluginSinceBuild=253

# --- Toolchain ---
javaVersion=21

# Opt-out flag for bundling Kotlin standard library -> https://jb.gg/intellij-platform-kotlin-stdlib
kotlin.stdlib.default.dependency=false
